version: '3.3'
services:
  app:
    image: smartosc-training:latest
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8004:8004"
# Names our volume
volumes:
  my-db:
    driver: local